// Backup recipe data
// paste example of data to work with here
// store in a specific variable and export in a specific variable to be able to access it from main js file

// -------------------------------------------------------------
// --------paste this part in js file if need backup data-------
// -------------------------------------------------------------
// // // // import backup data from separate file:
// // import { backupData } from './backupData.js'
// -------------------------------------------------------------
// -------------------------------------------------------------


export const backupData = {

  "results": [
    {
      "id": 634202,
      "image": "https://img.spoonacular.com/recipes/634202-312x231.jpg",
      "imageType": "jpg",
      "title": "Banana Walnut Cake",
      "readyInMinutes": 45,
      "servings": 16,
      "sourceUrl": "https://www.foodista.com/recipe/V72D6RQM/banana-walnut-cake",
      "vegetarian": true,
      "vegan": false,
      "glutenFree": false,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 6,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 0,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 18.5,
      "summary": "If you have approximately <b>45 minutes</b> to spend in the kitchen, Banana Walnut Cake might be a spectacular <b>lacto ovo vegetarian</b> recipe to try. One portion of this dish contains about <b>3g of protein</b>, <b>4g of fat</b>, and a total of <b>155 calories</b>. For <b>19 cents per serving</b>, you get a dessert that serves 16. This recipe is liked by 1 foodies and cooks. A mixture of walnuts, vegetable oil, sugar, and a handful of other ingredients are all it takes to make this recipe so tasty. It is brought to you by Foodista. This recipe is typical of Southern cuisine. Overall, this recipe earns a <b>not so great spoonacular score of 22%</b>. Similar recipes include <a href=\"https://spoonacular.com/recipes/banana-walnut-cake-916522\">Banana Walnut Cake</a>, <a href=\"https://spoonacular.com/recipes/banana-walnut-cake-1088018\">Banana & Walnut Cake</a>, and <a href=\"https://spoonacular.com/recipes/banana-walnut-cake-125214\">Banana Walnut Cake</a>.",
      "cuisines": [
        "Southern"
      ],
      "dishTypes": [
        "dessert"
      ],
      "diets": [
        "lacto ovo vegetarian"
      ],
      "occasions": [],
      "spoonacularScore": 13.351908683776855,
      "spoonacularSourceUrl": "https://spoonacular.com/banana-walnut-cake-634202"
    },
    {
      "id": 639900,
      "image": "https://img.spoonacular.com/recipes/639900-312x231.jpg",
      "imageType": "jpg",
      "title": "Colcannon",
      "readyInMinutes": 45,
      "servings": 8,
      "sourceUrl": "https://www.foodista.com/recipe/55V6MT85/colcannon",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 5,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 3,
      "healthScore": 9,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 49.24,
      "summary": "The recipe Colcannon is ready <b>in about 45 minutes</b> and is definitely an awesome <b>gluten free</b> option for lovers of European food. For <b>49 cents per serving</b>, you get a side dish that serves 8. One serving contains <b>163 calories</b>, <b>5g of protein</b>, and <b>6g of fat</b>. 3 people have tried and liked this recipe. Head to the store and pick up optional: 2 rashers bacon, potatoes, salt, and a few other things to make it today. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 56%</b>, which is good. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/colcannon-567589\">Colcannon</a>, <a href=\"https://spoonacular.com/recipes/colcannon-1080786\">Colcannon</a>, and <a href=\"https://spoonacular.com/recipes/colcannon-1261303\">Colcannon</a>.",
      "cuisines": [
        "European",
        "Irish"
      ],
      "dishTypes": [
        "side dish"
      ],
      "diets": [
        "gluten free"
      ],
      "occasions": [],
      "spoonacularScore": 55.44424057006836,
      "spoonacularSourceUrl": "https://spoonacular.com/colcannon-639900"
    },
    {
      "id": 660133,
      "image": "https://img.spoonacular.com/recipes/660133-312x231.jpg",
      "imageType": "jpg",
      "title": "Simple Roast Chicken",
      "readyInMinutes": 45,
      "servings": 4,
      "sourceUrl": "https://www.foodista.com/recipe/QFV873BT/simple-roast-chicken",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 28,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 2,
      "healthScore": 35,
      "creditsText": "foodista.com",
      "license": null,
      "sourceName": "foodista.com",
      "pricePerServing": 275.63,
      "summary": "Simple Roast Chicken is a <b>gluten free</b> recipe with 4 servings. For <b>$2.76 per serving</b>, this recipe <b>covers 37%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains about <b>47g of protein</b>, <b>64g of fat</b>, and a total of <b>990 calories</b>. It works well as a rather cheap main course. 2 people were glad they tried this recipe. From preparation to the plate, this recipe takes about <b>45 minutes</b>. It is brought to you by Foodista. Head to the store and pick up chicken, butter, lemon, and a few other things to make it today. Overall, this recipe earns a <b>solid spoonacular score of 69%</b>. Try <a href=\"https://spoonacular.com/recipes/simple-roast-chicken-1253951\">Simple Roast Chicken</a>, <a href=\"https://spoonacular.com/recipes/the-best-simple-roast-chicken-1510769\">The Best Simple Roast Chicken</a>, and <a href=\"https://spoonacular.com/recipes/simple-roast-chicken-697275\">Simple Roast Chicken</a> for similar recipes.",
      "cuisines": [],
      "dishTypes": [
        "lunch",
        "main course",
        "main dish",
        "dinner"
      ],
      "diets": [
        "gluten free"
      ],
      "occasions": [],
      "spoonacularScore": 80.87440490722656,
      "spoonacularSourceUrl": "https://spoonacular.com/simple-roast-chicken-660133"
    },
    {
      "id": 1095817,
      "image": "https://img.spoonacular.com/recipes/1095817-312x231.jpg",
      "imageType": "jpg",
      "title": "Super Food Trail Mix",
      "readyInMinutes": 5,
      "servings": 4,
      "sourceUrl": "https://www.foodista.com/recipe/4XP3H3DX/super-food-trail-mix",
      "vegetarian": true,
      "vegan": true,
      "glutenFree": true,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 5,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 7,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 123.81,
      "summary": "Super Food Trail Mix is a Mediterranean side dish. This recipe serves 4 and costs $1.24 per serving. Watching your figure? This gluten free, dairy free, paleolithic, and lacto ovo vegetarian recipe has <b>205 calories</b>, <b>6g of protein</b>, and <b>16g of fat</b> per serving. Head to the store and pick up walnut halves, blueberries, goji berries, and a few other things to make it today. 1 person has tried and liked this recipe. It is brought to you by Foodista. From preparation to the plate, this recipe takes about <b>5 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 47%</b>. This score is pretty good. If you like this recipe, you might also like recipes such as <a href=\"https://spoonacular.com/recipes/tropical-foods-trail-mix-brittle-663857\">Tropical Food’s Trail Mix Brittle</a>, <a href=\"https://spoonacular.com/recipes/tropical-foods-trail-mix-brittle-1631505\">Tropical Food’s Trail Mix Brittle</a>, and <a href=\"https://spoonacular.com/recipes/super-chunky-trail-mix-cookies-white-whole-wheat-flour-171751\">Super Chunky Trail Mix Cookies (White Whole Wheat Flour)</a>.",
      "cuisines": [
        "Mediterranean",
        "Italian",
        "European"
      ],
      "dishTypes": [
        "side dish"
      ],
      "diets": [
        "gluten free",
        "dairy free",
        "paleolithic",
        "lacto ovo vegetarian",
        "primal",
        "whole 30",
        "vegan"
      ],
      "occasions": [],
      "spoonacularScore": 51.25244140625,
      "spoonacularSourceUrl": "https://spoonacular.com/super-food-trail-mix-1095817"
    },
    {
      "id": 1160166,
      "image": "https://img.spoonacular.com/recipes/1160166-312x231.jpg",
      "imageType": "jpg",
      "title": "How to Make an Amazing Chicken Salad with Apples and Celery",
      "readyInMinutes": 10,
      "servings": 3,
      "sourceUrl": "https://www.pinkwhen.com/healthy-chicken-salad-with-apples/",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 13,
      "gaps": "no",
      "preparationMinutes": 10,
      "cookingMinutes": 0,
      "aggregateLikes": 5,
      "healthScore": 8,
      "creditsText": "pinkwhen.com",
      "license": null,
      "sourceName": "pinkwhen.com",
      "pricePerServing": 237.27,
      "summary": "You can never have too many main course recipes, so give How to Make an Amazing Chicken Salad with Apples and Celery a try. This recipe serves 3. Watching your figure? This gluten free recipe has <b>593 calories</b>, <b>60g of protein</b>, and <b>33g of fat</b> per serving. For <b>$2.37 per serving</b>, this recipe <b>covers 16%</b> of your daily requirements of vitamins and minerals. This recipe from Pink When has 5 fans. A mixture of celery, rotisserie chicken cut, avocado, and a handful of other ingredients are all it takes to make this recipe so delicious. From preparation to the plate, this recipe takes about <b>10 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 56%</b>, which is pretty good. <a href=\"https://spoonacular.com/recipes/how-to-make-an-amazing-chicken-salad-with-apples-and-celery-1398919\">How to Make an Amazing Chicken Salad with Apples and Celery</a>, <a href=\"https://spoonacular.com/recipes/how-to-make-an-amazing-chicken-salad-with-apples-and-celery-1401901\">How to Make an Amazing Chicken Salad with Apples and Celery</a>, and <a href=\"https://spoonacular.com/recipes/how-to-make-an-amazing-chicken-salad-with-apples-and-celery-1405063\">How to Make an Amazing Chicken Salad with Apples and Celery</a> are very similar to this recipe.",
      "cuisines": [],
      "dishTypes": [
        "lunch",
        "main course",
        "main dish",
        "dinner"
      ],
      "diets": [
        "gluten free"
      ],
      "occasions": [],
      "spoonacularScore": 57.16912841796875,
      "spoonacularSourceUrl": "https://spoonacular.com/how-to-make-an-amazing-chicken-salad-with-apples-and-celery-1160166"
    },
    {
      "id": 660130,
      "image": "https://img.spoonacular.com/recipes/660130-312x231.jpg",
      "imageType": "jpg",
      "title": "Simple Sage Pesto",
      "readyInMinutes": 45,
      "servings": 8,
      "sourceUrl": "https://www.foodista.com/recipe/VKKXPBQC/simple-sage-pesto",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 3,
      "gaps": "GAPS_FULL",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 26,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 95,
      "summary": "Simple Sage Pesto is a <b>gluten free and primal</b> recipe with 8 servings. One serving contains <b>95 calories</b>, <b>3g of protein</b>, and <b>9g of fat</b>. For <b>95 cents per serving</b>, this recipe <b>covers 8%</b> of your daily requirements of vitamins and minerals. Not a lot of people made this recipe, and 1 would say it hit the spot. A mixture of sage leaves, garlic cloves, salt and pepper, and a handful of other ingredients are all it takes to make this recipe so scrumptious. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is brought to you by Foodista. It works well as a condiment. Taking all factors into account, this recipe <b>earns a spoonacular score of 63%</b>, which is solid. Similar recipes include <a href=\"https://spoonacular.com/recipes/simple-gouda-and-sage-biscuits-619916\">Simple Goudan and Sage Biscuits</a>, <a href=\"https://spoonacular.com/recipes/simple-kohlrabi-with-pistachios-and-sage-948526\">simple kohlrabi with pistachios and sage</a>, and <a href=\"https://spoonacular.com/recipes/sage-walnut-pesto-46713\">Sage Walnut Pesto</a>.",
      "cuisines": [],
      "dishTypes": [
        "condiment",
        "dip",
        "sauce",
        "spread"
      ],
      "diets": [
        "gluten free",
        "primal"
      ],
      "occasions": [],
      "spoonacularScore": 74.20130920410156,
      "spoonacularSourceUrl": "https://spoonacular.com/simple-sage-pesto-660130"
    },
    {
      "id": 639850,
      "image": "https://img.spoonacular.com/recipes/639850-312x231.jpg",
      "imageType": "jpg",
      "title": "Cod with tomatoes, olives and polenta",
      "readyInMinutes": 45,
      "servings": 4,
      "sourceUrl": "https://www.foodista.com/recipe/R2VC8DFL/cod-with-tomatoes-olives-and-polenta",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 8,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 6,
      "healthScore": 36,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 334.32,
      "summary": "Cod with tomatoes, olives and polentan is a <b>gluten free, dairy free, and pescatarian</b> recipe with 4 servings. One portion of this dish contains approximately <b>25g of protein</b>, <b>19g of fat</b>, and a total of <b>345 calories</b>. For <b>$3.34 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista has 6 fans. It works well as a main course. A mixture of oregano, salt, corn polenta, and a handful of other ingredients are all it takes to make this recipe so tasty. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. With a spoonacular <b>score of 86%</b>, this dish is great. Users who liked this recipe also liked <a href=\"https://spoonacular.com/recipes/cod-with-leeks-tomatoes-olives-2331\">Cod With Leeks, Tomatoes & Olives</a>, <a href=\"https://spoonacular.com/recipes/roast-cod-with-little-tomatoes-and-assorted-olives-2344\">Roast Cod With Little Tomatoes And Assorted Olives</a>, and <a href=\"https://spoonacular.com/recipes/polenta-with-fresh-tomatoes-and-parmesan-crisps-polenta-made-easy-196413\">Polenta with Fresh Tomatoes and Parmesan Crisps | Polenta Made Easy</a>.",
      "cuisines": [],
      "dishTypes": [
        "lunch",
        "main course",
        "main dish",
        "dinner"
      ],
      "diets": [
        "gluten free",
        "dairy free",
        "pescatarian"
      ],
      "occasions": [],
      "spoonacularScore": 85.4424057006836,
      "spoonacularSourceUrl": "https://spoonacular.com/cod-with-tomatoes-olives-and-polenta-639850"
    },
    {
      "id": 641644,
      "image": "https://img.spoonacular.com/recipes/641644-312x231.jpg",
      "imageType": "jpg",
      "title": "Dreamy Chai Rice Pudding",
      "readyInMinutes": 45,
      "servings": 4,
      "sourceUrl": "https://www.foodista.com/recipe/CHRFL534/dreamy-chai-rice-pudding",
      "vegetarian": true,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 14,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 11,
      "healthScore": 12,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 489.23,
      "summary": "Dreamy Chai Rice Pudding might be a good recipe to expand your dessert recipe box. One serving contains <b>376 calories</b>, <b>11g of protein</b>, and <b>8g of fat</b>. This gluten free and lacto ovo vegetarian recipe serves 4 and costs <b>$4.89 per serving</b>. 11 person have made this recipe and would make it again. This recipe from Foodista requires brown sugar, vanillan essence, cardomon pods, and star anise. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 57%</b>, which is solid. Similar recipes include <a href=\"https://spoonacular.com/recipes/chai-rice-pudding-250814\">Chai Rice Pudding</a>, <a href=\"https://spoonacular.com/recipes/chai-rice-pudding-760284\">Chai Rice Pudding</a>, and <a href=\"https://spoonacular.com/recipes/vanilla-and-chai-rice-pudding-546678\">Vanillan and Chai rice pudding</a>.",
      "cuisines": [],
      "dishTypes": [
        "dessert"
      ],
      "diets": [
        "gluten free",
        "lacto ovo vegetarian"
      ],
      "occasions": [],
      "spoonacularScore": 62.90113830566406,
      "spoonacularSourceUrl": "https://spoonacular.com/dreamy-chai-rice-pudding-641644"
    },
    {
      "id": 636361,
      "image": "https://img.spoonacular.com/recipes/636361-312x231.jpg",
      "imageType": "jpg",
      "title": "Brussels Sprout With Mustard And Honey",
      "readyInMinutes": 45,
      "servings": 2,
      "sourceUrl": "https://www.foodista.com/recipe/SGFQWPWL/brussels-sprout-with-mustard-and-honey",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 7,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 39,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 238.06,
      "summary": "Brussels Sprout With Mustard And Honey could be just the <b>gluten free, dairy free, paleolithic, and primal</b> recipe you've been looking for. This recipe serves 2 and costs $2.38 per serving. One serving contains <b>272 calories</b>, <b>8g of protein</b>, and <b>14g of fat</b>. Head to the store and pick up salt and pepper, water, dijon mustard, and a few other things to make it today. 1 person has tried and liked this recipe. It works well as a side dish. It is brought to you by Foodista. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 78%</b>. This score is good. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/honey-mustard-brussels-sprout-slaw-580747\">Honey Mustard Brussels Sprout Slaw</a>, <a href=\"https://spoonacular.com/recipes/shredded-brussels-sprout-and-pomegranate-salad-with-honey-mustard-dressing-617655\">shredded brussels sprout and pomegranate salad with honey mustard dressing</a>, and <a href=\"https://spoonacular.com/recipes/brussels-sprout-slaw-with-mustard-dressing-and-maple-glazed-pecans-10858\">Brussels Sprout Slaw With Mustard Dressing And Maple-glazed Pecans</a>.",
      "cuisines": [],
      "dishTypes": [
        "side dish"
      ],
      "diets": [
        "gluten free",
        "dairy free",
        "paleolithic",
        "primal"
      ],
      "occasions": [],
      "spoonacularScore": 80.8260498046875,
      "spoonacularSourceUrl": "https://spoonacular.com/brussels-sprout-with-mustard-and-honey-636361"
    },
    {
      "id": 635468,
      "image": "https://img.spoonacular.com/recipes/635468-312x231.jpg",
      "imageType": "jpg",
      "title": "Blueberry Crumble Tart with Cream Cheese Whipped Cream",
      "readyInMinutes": 45,
      "servings": 12,
      "sourceUrl": "https://www.foodista.com/recipe/X2ZRBWCG/blueberry-crumble-tart-with-cream-cheese-whipped-cream",
      "vegetarian": true,
      "vegan": false,
      "glutenFree": false,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 14,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 2,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 81.05,
      "summary": "Blueberry Crumble Tart with Cream Cheese Whipped Cream is a <b>lacto ovo vegetarian</b> recipe with 12 servings. This dessert has <b>347 calories</b>, <b>5g of protein</b>, and <b>18g of fat</b> per serving. For <b>81 cents per serving</b>, this recipe <b>covers 9%</b> of your daily requirements of vitamins and minerals. 1 person has tried and liked this recipe. It is brought to you by Foodista. If you have baking powder, pastry flour, salt, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes around <b>45 minutes</b>. With a spoonacular <b>score of 28%</b>, this dish is not so excellent. <a href=\"https://spoonacular.com/recipes/blueberry-crumble-tart-with-cream-cheese-whipped-cream-1636461\">Blueberry Crumble Tart with Cream Cheese Whipped Cream</a>, <a href=\"https://spoonacular.com/recipes/strawberry-cream-cheese-crumble-tart-507841\">Strawberry Cream Cheese Crumble Tart</a>, and <a href=\"https://spoonacular.com/recipes/blueberry-cream-cheese-muffins-with-chocolate-crumble-560262\">Blueberry Cream Cheese Muffins with Chocolate Crumble</a> are very similar to this recipe.",
      "cuisines": [],
      "dishTypes": [
        "dessert"
      ],
      "diets": [
        "lacto ovo vegetarian"
      ],
      "occasions": [],
      "spoonacularScore": 33.21874237060547,
      "spoonacularSourceUrl": "https://spoonacular.com/blueberry-crumble-tart-with-cream-cheese-whipped-cream-635468"
    },
    {
      "id": 640666,
      "image": "https://img.spoonacular.com/recipes/640666-312x231.jpg",
      "imageType": "jpg",
      "title": "Creamy Mushrooms Over Soba Noodles (Vegan)",
      "readyInMinutes": 45,
      "servings": 4,
      "sourceUrl": "https://www.foodista.com/recipe/FJXT4TLQ/creamy-mushrooms-over-soba-noodles-vegan",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": false,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 19,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 3,
      "healthScore": 15,
      "creditsText": "foodista.com",
      "license": null,
      "sourceName": "foodista.com",
      "pricePerServing": 254.24,
      "summary": "Creamy Mushrooms Over Soba Noodles (Vegan) is a main course that serves 4. One serving contains <b>587 calories</b>, <b>23g of protein</b>, and <b>24g of fat</b>. For <b>$2.54 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. 3 people were glad they tried this recipe. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. This recipe from Foodista requires mushrooms, white wine, juice of lemon, and thyme. It is a good option if you're following a <b>dairy free</b> diet. Overall, this recipe earns a <b>solid spoonacular score of 59%</b>. Similar recipes include <a href=\"https://spoonacular.com/recipes/sweet-sour-soba-noodles-with-three-mushrooms-478539\">Sweet-sour soba noodles with three mushrooms</a>, <a href=\"https://spoonacular.com/recipes/soba-noodles-with-roasted-tomatoes-mushrooms-and-eggs-602855\">Soba Noodles with Roasted Tomatoes, Mushrooms and Eggs</a>, and <a href=\"https://spoonacular.com/recipes/black-bean-soba-noodles-with-mushrooms-cabbage-211612\">Black bean soba noodles with mushrooms & cabbage</a>.",
      "cuisines": [],
      "dishTypes": [
        "side dish",
        "lunch",
        "main course",
        "main dish",
        "dinner"
      ],
      "diets": [
        "dairy free"
      ],
      "occasions": [],
      "spoonacularScore": 63.37925338745117,
      "spoonacularSourceUrl": "https://spoonacular.com/creamy-mushrooms-over-soba-noodles-vegan-640666"
    },
    {
      "id": 1095746,
      "image": "https://img.spoonacular.com/recipes/1095746-312x231.jpg",
      "imageType": "jpg",
      "title": "Lemon and Edamame Risotto with Pecans",
      "readyInMinutes": 50,
      "servings": 4,
      "sourceUrl": "https://www.foodista.com/recipe/XDHRLR2D/lemon-and-edamame-bean-risotto-with-pecans",
      "vegetarian": true,
      "vegan": true,
      "glutenFree": true,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 11,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 20,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 190.23,
      "summary": "Lemon and Edamame Risotto with Pecans takes about <b>50 minutes</b> from beginning to end. One portion of this dish contains around <b>8g of protein</b>, <b>14g of fat</b>, and a total of <b>366 calories</b>. For <b>$1.9 per serving</b>, you get a hor d'oeuvre that serves 4. 1 person found this recipe to be delicious and satisfying. It is brought to you by Foodista. Head to the store and pick up garlic clove, pecan nuts, parsley, and a few other things to make it today. Only a few people really liked this Mediterranean dish. It is a good option if you're following a <b>gluten free, dairy free, lacto ovo vegetarian, and vegan</b> diet. With a spoonacular <b>score of 66%</b>, this dish is good. Similar recipes include <a href=\"https://spoonacular.com/recipes/risotto-with-edamame-lemon-zest-and-tarragon-36010\">Risotto With Edamame, Lemon Zest, and Tarragon</a>, <a href=\"https://spoonacular.com/recipes/risotto-with-edamame-338234\">Risotto with Edamame</a>, and <a href=\"https://spoonacular.com/recipes/risotto-with-edamame-arugula-porcini-8897\">Risotto With Edamame, Arugula & Porcini</a>.",
      "cuisines": [
        "Mediterranean",
        "Italian",
        "European"
      ],
      "dishTypes": [
        "side dish",
        "antipasti",
        "starter",
        "snack",
        "appetizer",
        "antipasto",
        "hor d'oeuvre"
      ],
      "diets": [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian",
        "vegan"
      ],
      "occasions": [],
      "spoonacularScore": 72.24285888671875,
      "spoonacularSourceUrl": "https://spoonacular.com/lemon-and-edamame-risotto-with-pecans-1095746"
    },
    {
      "id": 652413,
      "image": "https://img.spoonacular.com/recipes/652413-312x231.jpg",
      "imageType": "jpg",
      "title": "Moroccan Carrot Soup",
      "readyInMinutes": 45,
      "servings": 2,
      "sourceUrl": "https://www.foodista.com/recipe/TLKVZLVG/moroccan-carrot-soup",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 11,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 5,
      "healthScore": 14,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 225.31,
      "summary": "The recipe Moroccan Carrot Soup can be made <b>in about 45 minutes</b>. This recipe makes 2 servings with <b>349 calories</b>, <b>11g of protein</b>, and <b>16g of fat</b> each. For <b>$2.25 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. It works well as a rather inexpensive hor d'oeuvre. It can be enjoyed any time, but it is especially good for <b>Autumn</b>. A mixture of butter, onion, honey, and a handful of other ingredients are all it takes to make this recipe so yummy. It is brought to you by Foodista. 5 people were impressed by this recipe. It is a good option if you're following a <b>gluten free</b> diet. Taking all factors into account, this recipe <b>earns a spoonacular score of 57%</b>, which is solid. If you like this recipe, you might also like recipes such as <a href=\"https://spoonacular.com/recipes/moroccan-carrot-soup-542567\">Moroccan Carrot Soup</a>, <a href=\"https://spoonacular.com/recipes/moroccan-carrot-soup-155980\">Moroccan Carrot Soup</a>, and <a href=\"https://spoonacular.com/recipes/moroccan-carrot-soup-971196\">Moroccan Carrot Soup</a>.",
      "cuisines": [],
      "dishTypes": [
        "antipasti",
        "soup",
        "starter",
        "snack",
        "appetizer",
        "antipasto",
        "hor d'oeuvre"
      ],
      "diets": [
        "gluten free"
      ],
      "occasions": [
        "fall",
        "winter"
      ],
      "spoonacularScore": 63.989990234375,
      "spoonacularSourceUrl": "https://spoonacular.com/moroccan-carrot-soup-652413"
    },
    {
      "id": 665719,
      "image": "https://img.spoonacular.com/recipes/665719-312x231.jpg",
      "imageType": "jpg",
      "title": "Zucchini Buckwheat Pancakes",
      "readyInMinutes": 45,
      "servings": 20,
      "sourceUrl": "https://www.foodista.com/recipe/32WJ7SFT/zucchini-buckwheat-pancakes",
      "vegetarian": true,
      "vegan": false,
      "glutenFree": false,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 1,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 0,
      "creditsText": "foodista.com",
      "license": null,
      "sourceName": "foodista.com",
      "pricePerServing": 17.99,
      "summary": "Zucchini Buckwheat Pancakes might be just the breakfast you are searching for. This recipe serves 20 and costs 18 cents per serving. One serving contains <b>60 calories</b>, <b>2g of protein</b>, and <b>4g of fat</b>. This recipe is liked by 1 foodies and cooks. It is brought to you by Foodista. If you have buckwheat flour, shallots, parsley, and a few other ingredients on hand, you can make it. It is a good option if you're following a <b>lacto ovo vegetarian</b> diet. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 19%</b>. This score is not so amazing. Try <a href=\"https://spoonacular.com/recipes/buckwheat-pancakes-1637517\">Buckwheat Pancakes</a>, <a href=\"https://spoonacular.com/recipes/buckwheat-pancakes-1278603\">Buckwheat Pancakes</a>, and <a href=\"https://spoonacular.com/recipes/buckwheat-pancakes-691752\">Buckwheat Pancakes</a> for similar recipes.",
      "cuisines": [],
      "dishTypes": [
        "morning meal",
        "brunch",
        "breakfast"
      ],
      "diets": [
        "lacto ovo vegetarian"
      ],
      "occasions": [],
      "spoonacularScore": 5.753255844116211,
      "spoonacularSourceUrl": "https://spoonacular.com/zucchini-buckwheat-pancakes-665719"
    },
    {
      "id": 654331,
      "image": "https://img.spoonacular.com/recipes/654331-312x231.jpg",
      "imageType": "jpg",
      "title": "Paella Catalane With Mussels, Squid & Crevettes",
      "readyInMinutes": 45,
      "servings": 10,
      "sourceUrl": "https://www.foodista.com/recipe/SVHX43GF/paella-catalane-with-mussels-squid-crevettes",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 20,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 17,
      "creditsText": "foodista.com",
      "license": null,
      "sourceName": "foodista.com",
      "pricePerServing": 221.48,
      "summary": "Paella Catalane With Mussels, Squid & Crevettes might be just the main course you are searching for. This recipe makes 10 servings with <b>668 calories</b>, <b>35g of protein</b>, and <b>37g of fat</b> each. For <b>$2.21 per serving</b>, this recipe <b>covers 24%</b> of your daily requirements of vitamins and minerals. This recipe is liked by 1 foodies and cooks. This recipe from Foodista requires freshly cracked pepper, chorizo, onion, and butter. It is a good option if you're following a <b>gluten free</b> diet. It is a <b>reasonably priced</b> recipe for fans of European food. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. With a spoonacular <b>score of 52%</b>, this dish is good. Try <a href=\"https://spoonacular.com/recipes/angel-hair-pasta-with-squid-mussels-and-zucchini-1368459\">Angel Hair Pasta with Squid, Mussels and Zucchini</a>, <a href=\"https://spoonacular.com/recipes/angel-hair-pasta-with-squid-mussels-and-zucchini-28356\">Angel Hair Pasta with Squid, Mussels and Zucchini</a>, and <a href=\"https://spoonacular.com/recipes/quick-paella-with-shrimp-mussels-76786\">Quick Paella With Shrimp & Mussels</a> for similar recipes.",
      "cuisines": [
        "Spanish",
        "European"
      ],
      "dishTypes": [
        "lunch",
        "main course",
        "main dish",
        "dinner"
      ],
      "diets": [
        "gluten free"
      ],
      "occasions": [],
      "spoonacularScore": 8.988890647888184,
      "spoonacularSourceUrl": "https://spoonacular.com/paella-catalane-with-mussels-squid-crevettes-654331"
    },
    {
      "id": 660094,
      "image": "https://img.spoonacular.com/recipes/660094-312x231.jpg",
      "imageType": "jpg",
      "title": "Simple Egg Salad",
      "readyInMinutes": 45,
      "servings": 1,
      "sourceUrl": "https://www.foodista.com/recipe/6R26TKMK/simple-egg-salad",
      "vegetarian": true,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": true,
      "weightWatcherSmartPoints": 8,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 2,
      "healthScore": 2,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 50.65,
      "summary": "If you want to add more <b>gluten free, dairy free, lacto ovo vegetarian, and fodmap friendly</b> recipes to your repertoire, Simple Egg Salad might be a recipe you should try. One portion of this dish contains approximately <b>7g of protein</b>, <b>26g of fat</b>, and a total of <b>268 calories</b>. This recipe serves 1 and costs 51 cents per serving. 2 people were glad they tried this recipe. Not a lot of people really liked this hor d'oeuvre. It is brought to you by Foodista. If you have paprika, chives, dijon mustard, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. Taking all factors into account, this recipe <b>earns a spoonacular score of 25%</b>, which is rather bad. Try <a href=\"https://spoonacular.com/recipes/simple-egg-salad-491609\">Simple Egg Salad</a>, <a href=\"https://spoonacular.com/recipes/simple-homemade-egg-salad-sandwich-99412\">Simple Homemade Egg Salad Sandwich</a>, and <a href=\"https://spoonacular.com/recipes/how-to-make-simple-egg-free-caesar-salad-dressing-1010229\">how to make simple egg-free caesar salad dressing</a> for similar recipes.",
      "cuisines": [],
      "dishTypes": [
        "side dish",
        "antipasti",
        "starter",
        "snack",
        "appetizer",
        "antipasto",
        "hor d'oeuvre"
      ],
      "diets": [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian",
        "fodmap friendly",
        "whole 30"
      ],
      "occasions": [],
      "spoonacularScore": 34.3165168762207,
      "spoonacularSourceUrl": "https://spoonacular.com/simple-egg-salad-660094"
    },
    {
      "id": 1697559,
      "image": "https://img.spoonacular.com/recipes/1697559-312x231.jpg",
      "imageType": "jpg",
      "title": "Pork Chops with Apple - a taste of fall in 30 minutes",
      "readyInMinutes": 35,
      "servings": 2,
      "sourceUrl": "https://maplewoodroad.com/pork-chops-with-apple/",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 20,
      "gaps": "no",
      "preparationMinutes": 10,
      "cookingMinutes": 25,
      "aggregateLikes": 0,
      "healthScore": 22,
      "creditsText": "maplewoodroad",
      "license": "spoonacular's terms",
      "sourceName": "Maplewood Road",
      "pricePerServing": 272.65,
      "summary": "Pork Chops with Apple - a taste of fall in 30 minutes is a <b>gluten free</b> main course. This recipe makes 2 servings with <b>718 calories</b>, <b>39g of protein</b>, and <b>48g of fat</b> each. For <b>$2.73 per serving</b>, this recipe <b>covers 33%</b> of your daily requirements of vitamins and minerals. It is brought to you by spoonacular user <a href=\"/profile/maplewoodroad\">maplewoodroad</a>. From preparation to the plate, this recipe takes around <b>35 minutes</b>. If you have pork chops, salt and pepper, dijon mustard, and a few other ingredients on hand, you can make it. It will be a hit at your <b>Autumn</b> event. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/pork-chops-with-apples-a-fall-classic-579886\">Pork Chops with Apples: A fall classic</a>, <a href=\"https://spoonacular.com/recipes/taste-of-fall-salad-405253\">Taste-of-Fall Salad</a>, and <a href=\"https://spoonacular.com/recipes/knocks-and-chops-knockwurst-with-spiced-sauerkraut-and-smoked-pork-chops-with-bacon-apple-and-onion-379237\">Knocks and Chops: Knockwurst with Spiced Sauerkraut and Smoked Pork Chops with Bacon, Apple and Onion</a>.",
      "cuisines": [],
      "dishTypes": [
        "lunch",
        "main course",
        "main dish",
        "dinner"
      ],
      "diets": [
        "gluten free"
      ],
      "occasions": [
        "fall"
      ],
      "spoonacularScore": 65.84951782226562,
      "spoonacularSourceUrl": "https://spoonacular.com/pork-chops-with-apple-a-taste-of-fall-in-30-minutes-1697559"
    },
    {
      "id": 648850,
      "image": "https://img.spoonacular.com/recipes/648850-312x231.jpg",
      "imageType": "jpg",
      "title": "Keylime Cheesecake Pie",
      "readyInMinutes": 45,
      "servings": 10,
      "sourceUrl": "https://www.foodista.com/recipe/KQ5NVDFS/keylime-cheesecake-pie",
      "vegetarian": false,
      "vegan": false,
      "glutenFree": false,
      "dairyFree": false,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 15,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 1,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 88.09,
      "summary": "Keylime Cheesecake Pie requires about <b>45 minutes</b> from start to finish. This recipe serves 10 and costs 88 cents per serving. One serving contains <b>296 calories</b>, <b>6g of protein</b>, and <b>16g of fat</b>. A mixture of cream cheese, graham cracker pie shell, condensed milk, and a handful of other ingredients are all it takes to make this recipe so yummy. 1 person has made this recipe and would make it again. It is brought to you by Foodista. With a spoonacular <b>score of 21%</b>, this dish is not so tremendous. Users who liked this recipe also liked <a href=\"https://spoonacular.com/recipes/cheesecake-pie-131312\">Cheesecake Pie</a>, <a href=\"https://spoonacular.com/recipes/cheesecake-pie-449138\">Cheesecake Pie</a>, and <a href=\"https://spoonacular.com/recipes/coffee-cheesecake-pie-267677\">Coffee Cheesecake Pie</a>.",
      "cuisines": [],
      "dishTypes": [],
      "diets": [],
      "occasions": [],
      "spoonacularScore": 28.08840560913086,
      "spoonacularSourceUrl": "https://spoonacular.com/keylime-cheesecake-pie-648850"
    },
    {
      "id": 868800,
      "image": "https://img.spoonacular.com/recipes/868800-312x231.png",
      "imageType": "png",
      "title": "Easy Avocado Egg Quinoa Breakfast Bowl",
      "readyInMinutes": 45,
      "servings": 2,
      "sourceUrl": "https://fullbellysisters.blogspot.com/2017/03/easy-avocado-egg-quinoa-blend-breakfast.html",
      "vegetarian": true,
      "vegan": false,
      "glutenFree": true,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 10,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 0,
      "healthScore": 12,
      "creditsText": "Full Belly Sisters",
      "license": "CC BY-SA 3.0",
      "sourceName": "Full Belly Sisters",
      "pricePerServing": 200.57,
      "summary": "Easy Avocado Egg Quinoa Breakfast Bowl is a <b>gluten free, dairy free, and lacto ovo vegetarian</b> recipe with 2 servings. For <b>$2.01 per serving</b>, this recipe <b>covers 20%</b> of your daily requirements of vitamins and minerals. One portion of this dish contains around <b>14g of protein</b>, <b>23g of fat</b>, and a total of <b>326 calories</b>. This recipe from fullbellysisters.blogspot.com has 1 fans. It works well as a breakfast. A mixture of goya quinoa blend, lime juice, eggs, and a handful of other ingredients are all it takes to make this recipe so delicious. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. Overall, this recipe earns an <b>improvable spoonacular score of 0%</b>. Similar recipes are <a href=\"https://spoonacular.com/recipes/avocado-sweet-lassi-how-to-make-avocado-lassi-indian-avocado-1681409\">Avocado Sweet Lassi - How to make Avocado Lassi - Indian Avocado</a>, <a href=\"https://spoonacular.com/recipes/instant-pot-quinoa-grain-bowl-982371\">Instant Pot Quinoa Grain Bowl</a>, and <a href=\"https://spoonacular.com/recipes/mexican-quinoa-bowl-1646941\">Mexican Quinoa Bowl</a>.",
      "cuisines": [],
      "dishTypes": [
        "morning meal",
        "brunch",
        "breakfast"
      ],
      "diets": [
        "gluten free",
        "dairy free",
        "lacto ovo vegetarian"
      ],
      "occasions": [],
      "spoonacularScore": 53.925559997558594,
      "spoonacularSourceUrl": "https://spoonacular.com/easy-avocado-egg-quinoa-breakfast-bowl-868800"
    },
    {
      "id": 642547,
      "image": "https://img.spoonacular.com/recipes/642547-312x231.jpg",
      "imageType": "jpg",
      "title": "Indian-Inspired Falafel Appetizer",
      "readyInMinutes": 45,
      "servings": 12,
      "sourceUrl": "https://www.foodista.com/recipe/X86M5N75/falafel-with-an-indian-twist",
      "vegetarian": true,
      "vegan": true,
      "glutenFree": false,
      "dairyFree": true,
      "veryHealthy": false,
      "cheap": false,
      "veryPopular": false,
      "sustainable": false,
      "lowFodmap": false,
      "weightWatcherSmartPoints": 2,
      "gaps": "no",
      "preparationMinutes": null,
      "cookingMinutes": null,
      "aggregateLikes": 1,
      "healthScore": 10,
      "creditsText": "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
      "license": "CC BY 3.0",
      "sourceName": "Foodista",
      "pricePerServing": 61.72,
      "summary": "Indian-Inspired Falafel Appetizer could be just the <b>dairy free, lacto ovo vegetarian, and vegan</b> recipe you've been looking for. For <b>62 cents per serving</b>, you get a hor d'oeuvre that serves 12. One portion of this dish contains about <b>3g of protein</b>, <b>4g of fat</b>, and a total of <b>102 calories</b>. 1 person found this recipe to be scrumptious and satisfying. It is a <b>very affordable</b> recipe for fans of middl eastern food. If you have garlic cloves, garbanzo beans/ chickpeas, salt, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is brought to you by Foodista. All things considered, we decided this recipe <b>deserves a spoonacular score of 83%</b>. This score is tremendous. If you like this recipe, take a look at these similar recipes: <a href=\"https://spoonacular.com/recipes/indian-inspired-lentil-soup-647874\">Indian-Inspired Lentil Soup</a>, <a href=\"https://spoonacular.com/recipes/indian-inspired-chicken-kabobs-276442\">Indian-Inspired Chicken Kabobs</a>, and <a href=\"https://spoonacular.com/recipes/onion-salad-indian-inspired-145401\">Onion Salad - Indian Inspired</a>.",
      "cuisines": [
        "Middle Eastern"
      ],
      "dishTypes": [
        "antipasti",
        "starter",
        "snack",
        "appetizer",
        "antipasto",
        "hor d'oeuvre"
      ],
      "diets": [
        "dairy free",
        "lacto ovo vegetarian",
        "vegan"
      ],
      "occasions": [],
      "spoonacularScore": 54.35655212402344,
      "spoonacularSourceUrl": "https://spoonacular.com/indian-inspired-falafel-appetizer-642547"
    }
  ],
  "offset": 0,
  "number": 20,
  "totalResults": 5224
}
